### ISSUE TITLE
Saner default configuration in motley_cue.conf

### ISSUE THREAD

**Issue by dianagudu** [dianagudu/motley_cue#16]
- add more supported IdPs to the list
- reasonable default groups authorised
- remove m-team as default authorised group

**Comment by dianagudu** [comment]
> * add more supported IdPs to the list
> * remove m-team as default authorised group

Done in ff8bd37eb50c607cd353ee1f12e5c8f229d6dc57

> * reasonable default groups authorised

What are reasonable defaults? It's probably more secure to not authorise any groups by default. We can still provide a default list of supported OPs, although without additional authorisation configured, no users will be authorised.

For example, in the provided [etc/motley_cue.conf](https://github.com/dianagudu/motley_cue/blob/master/etc/motley_cue.conf) the KIT IdP is supported but no one is authorised to use the service.

**Comment by marcvs** [comment]
Very nice, that new config.

I'd say that the config should contain a lot of examples, that should work in practice, but they're all commented out.
One example missing would be an individual user (e.g. yours).
A cmdline example in which e.g. mccli shows your id (and groups / entitlements) would be nice to be shown in that config file, too.

Did you extend flaat for this, or did you code things yourself?

**Comment by dianagudu** [comment]
> Very nice, that new config.
> 
> I'd say that the config should contain a lot of examples, that should work in practice, but they're all commented out.
> One example missing would be an individual user (e.g. yours).

Good point.

> A cmdline example in which e.g. mccli shows your id (and groups / entitlements) would be nice to be shown in that config file, too.

That would be nice. I'll get on the mccli issues next, so this is another feature I could add.

> 
> Did you extend flaat for this, or did you code things yourself?

No, I coded things myself. It's more a matter of parsing the authorisation rules in the config and using the appropriate decorators in flaat. Gabriel's idea about an authorisation rule engine and a well defined language would make sense here if we wanted to define something more complex, and then it definitely should be integrated in flaat.

**Comment by dianagudu** [comment]
Fixed in e9b96942f7fa522d27b235f82c84709e6603ff29 (and 022ba7b85318cadcce914642371a7a091de20ab4 for admin config examples).

For this part:
> A cmdline example in which e.g. mccli shows your id (and groups / entitlements) would be nice to be shown in that config file, too.

there is an example on using `flaat-userinfo` instead. Can be updated if this feature is added to `mccli` as well.
