### ISSUE TITLE
systemctl reload motley-cue

### ISSUE THREAD

**Issue by dianagudu** [dianagudu/motley_cue#17]
systemd service does not provide reload capability

**Comment by marcvs** [comment]
You mean adding `systemctl restart motley-cue` in the `%postin` stance of the rpm / deb package?

**Comment by dianagudu** [comment]
No, I just mean the possibility to do `systemctl reload motley-cue`, which differs from `restart` in that it reloads the service configuration without fully shutting down and starting up again (an `ExecReload=...` line in the systemd service file).
