### ISSUE TITLE
Possible relocation issue in the new motley-cue version 0.3.0-2.

### ISSUE THREAD

**Issue by benoitroland** [dianagudu/motley_cue#42]
Dear all,

when trying to install the new motley-cue version 0.3.0-2, I got a error `status=203/EXEC` which points to some issue with the interpreter. Looking at the difference between the new (0.3.0-2) and previous (0.3.0-1) versions, I found a different shebang in the executable `/usr/lib/motley-cue/bin/gunicorn`:

0.3.0-1: first line: #!/usr/lib/motley-cue/bin/python
0.3.0-2: first line: #!/builds/m-team/motley_cue/venv/bin/python

which is at the origin of the problem.

Replacing the shebang by the previous one makes the installation successfull.

Would it be possible to build a new rpm for the motley-cue package?

Thanks a lot in advance for your help!
Benoit

**Comment by dianagudu** [comment]
Hi there,

Thanks for pointing this out! The rpm build seems to have bug in the post-installation phase, which was fixing the shebangs in the installed python executables...

I'll look into this, but in light of the [feudalAdapter issue](https://git.scc.kit.edu/feudal/feudalAdapterLdf/-/issues/71) being reopened, I'd suggest you stick with version `0.3.0-1` until we release a fix for feudal.

**Comment by dianagudu** [comment]
Fixed by 3235850c9f730375776cbc982dcee51e482bfadd.
