### ISSUE TITLE
Two motley-cue repos

### ISSUE THREAD

**Issue by marcvs** [dianagudu/motley_cue#45]
When searching for motley-cue on github, I find dianagudu and kitedu.

One way to address this is to add two remotes for one branch:

```
> push to two remotes at the sme time
git remote set-url --add --push origin git://original/repo.git
git remote set-url --add --push origin git://another/repo.git
```
But this only works for the current branch, not for all future branches.

**Comment by dianagudu** [comment]
Removed the repo under [kit-scc](https://github.com/KIT-SCC/motley_cue), [this](https://github.com/dianagudu/motley_cue/) is the reference repo.
