### ISSUE TITLE
dockerised builds fail with unknown instruction: -E

### ISSUE THREAD

**Issue by marcvs** [dianagudu/motley_cue#5]
Apparently a '-e' in the echo command in the Makefile for all `docker build` commands causes an error

**Comment by dianagudu** [comment]
I cannot reproduce this.
In my case, the opposite happens: docker build fails _without_ -e (which enables interpretation of backslash escapes):

```
$ make dockerised_deb_debian_buster
echo "\ndebian_buster"
\ndebian_buster
Sending build context to Docker daemon  232.2MB
Error response from daemon: dockerfile parse error line 1: FROM requires either one or three arguments
make: *** [Makefile:57: docker_debian_buster] Error 1
```

**Comment by marcvs** [comment]
It's probably related to this one:
https://unix.stackexchange.com/questions/88307/escape-sequences-with-echo-e-in-different-shells
bash and sh handle -e or non -e differently.

**Comment by marcvs** [comment]
Should be fixed now.
